[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 13

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1
blur = true
# decorations = "none"

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = { blinking = "Always" }

[general]
# import = ["~/.config/alacritty/themes/horizon-dark.toml"]
# import = ["~/.config/alacritty/themes/github-dark-default.toml"]
# import = ["~/.config/alacritty/themes/github-light-default.toml"]
# import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]
import = ["~/.config/alacritty/themes/vscode-dark.toml"]

# [env]
# term = "xterm-256color"
