[font]
normal = { family = "CaskaydiaCove NF" }
size = 13

[window]
dynamic_title = true
dynamic_padding = true
opacity = 1
blur = true
decorations = "none"

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
style = { blinking = "Always" }

[general]
import = ["~/.config/alacritty/themes/carbonfox.toml"]

# [env]
# term = "xterm-256color"
